### ISSUE TITLE
Can't seem to parse #f3f3f3?

### ISSUE THREAD

**Issue by joshgoebel** [Myndex/colorparsley#2]
```
colorParsley error: unable to parse string
#F3F3F3 [ 0, 0, 0, '', false, 'parsleyError' ]
```

Bug in the regex?

Related: https://github.com/highlightjs/highlight.js/issues/3483

**Comment by Myndex** [comment]
Thank you @joshgoebel  this is an uppercase.lowercase issue, should be fixed today and updated. OOOPS, it's supposed to set all to lowercase before sending to regex.

**Comment by Myndex** [comment]
FIxed and published, thank you @joshgoebel
