### ISSUE TITLE
Tests and testability

### ISSUE THREAD

**Issue by phloe** [Myndex/colorparsley#5]
I'm thinking it would be helpful to have a set of tests (instead of/in addition to the test.html) to track whether the functions return what is expected?

The test.html currently just outputs what the functions return; not if it's correct/expected.

I have a [separate branch](https://github.com/phloe/colorparsley/tree/tests) with added tests that can be run in the console:

<img width="335" alt="Screenshot 2022-05-15 at 19 33 00" src="https://user-images.githubusercontent.com/13237/168486193-0bd068d4-d039-48dc-b982-a430a3093b91.png">

Tests can also be used test invalid inputs:

`colorParsley('rgb(256, 100%, 127)')` currently gives `[256, 1, 127, 1, true, 'rgb']` - when it should probably have failed?

256 gets matched bc the regexp is too lax. To match exact 0-255 values you will need something like: `/1?[0-9]{1,2}|2[0-4][0-9]|25[0-5]/`.

As you can imagine adding this all the needed places to the existing regexp will result in an even more unwieldy regexp.
Maybe it would be a good idea to split up the parsing of color strings into a series of smaller more easily maintainable routines/regexps?

The correctness would be easier to ensure - and addition of parsing of new emerging color notations would be easier too 🙂

**Comment by Myndex** [comment]
Hey Rasmus @phloe 

Thank you for all of your feedback!!!! Much appreciated.

Yes, "real" tests would be awesome... the test.html is just what I use while I'm working on things, and there I know what it "should" be, definitely would be better to have automatable testing.


> _colorParsley('rgb(256, 100%, 127)') currently gives [256, 1, 127, 1, true, 'rgb'] - when it should probably have failed?_

Hmmm, that's not good... I'll look into it.

The Regex WAS stricter, but the advent of CSS4 introduced a lot of "WTF" such as defining float values as 0.0-255.0 (the idea being compatibility)  but 256 should be clamped at 255, and 100% should be converted to 255 (then it is a color channel) or 1 (only when it is an alpha channel) this is for compatibility with CSS4.

It looks like rgb/rgba might be transiting through the "kitchen sink" part of the regex, which accepts things like hsv() or luv(). But rgb() and rgba() should be blocked from that part of the chain.

I'll take a look and see where the goof is.

Thank you!

**Comment by cmcculloh-kr** [comment]
@phloe Are you planning to issue a pull-request with your tests?

Another one to test: `rgba(0,0,0,0)` currently seems to be returning `[0,0,0,1,true,'sRGB']`, which should not be the case. It should be  `[0,0,0,0,true,'sRGB']`

**Comment by phloe** [comment]
Sure!

The PR is open now: https://github.com/Myndex/colorparsley/pull/6

**Comment by Myndex** [comment]
Hi @cormacmccarthy 

> Another one to test: `rgba(0,0,0,0)` currently seems to be returning `[0,0,0,1,true,'sRGB']`, which should not be the case. It should be `[0,0,0,0,true,'sRGB']`

That's not good, I'll look into it asap, thank you.

**Comment by Myndex** [comment]
Merged, thank you guys!

Keeping this issue open till I find the alpha bug there...

**Comment by Myndex** [comment]
Hi @cormacmccarthy 
> Another one to test: `rgba(0,0,0,0)` currently seems to be returning `[0,0,0,1,true,'sRGB']`, which should not be the case. It should be `[0,0,0,0,true,'sRGB']`

I am getting:

    color 7: rgb(0,0,0,0)  	 array: [0,0,0,0,true,sRGB] 

So I am not sure as to why you're getting a different response? Two questions:

1) Are you using colorparsley  0.1.6 and
2) Is this actually related to Bridge PCA or APCA?

**Comment by Myndex** [comment]
Hi @cormacmccarthy

I can't recreate the error, but I did update and publish version 0.1.7 which includes the test scripts and some other adjustments. Im going to close this issue, but fel free to open a new on if you are stil having probles.

Thank you!
